fix:[CORE-769]/rename_policyaction_to_policy_in_notification
PaladinCloud/CE pull request #1308
Opened 2023-06-16 08:46 UTC by akashpaladin

# Description
Rename ‘Policyaction’ to ‘Policy’
[CORE-769]
Fixes # (issue)
[CORE-769]
## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Chore (no code changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also
list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] My commit message/PR follows the contribution guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# **Other information**:

List any documentation updates that are needed for the Wiki

2023-06-16 08:49 UTC, dheerajkholia-paladin approved these changes

2023-06-16 10:27 UTC, plyubich commented
Can we please make sure that the rest of the names are also singles and not plural.

Example:
Violations -> Violation

2023-06-19 16:28 UTC, raviteja-mandala requested changes
In fetchNotificationSettings commonUtils class , corresponding changes should be done.

2023-06-21 05:12 UTC, raviteja-mandala approved these changes

2023-06-22 05:17 UTC, santhosh-challa approved these changes

2023-06-22 05:17 UTC, merged