feat:[CUS-147] Cost Policy-Remove Unused Load Balancers
PaladinCloud/CE pull request #1388
Opened 2023-07-19 08:04 UTC by kushZemoso

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List
any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Chore (no code changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also
list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] My commit message/PR follows the contribution guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# **Other information**:

List any documentation updates that are needed for the Wiki

2023-07-20 10:13 UTC, arunpaladin requested changes
at line 97 can you add null check condition.

2023-07-20 10:34 UTC, kushZemoso commented on jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/azurerules/LoadBalancer/RemoveUnusedLoadBalancer.java
> +                annotation.put(PacmanSdkConstants.DESCRIPTION,"Ensure Network Security Group Flow Log retention for more than 90 days");
Done

2023-07-20 10:35 UTC, santhosh-challa approved these changes

2023-07-21 09:19 UTC, arunpaladin approved these changes

2023-07-21 09:19 UTC, arunpaladin commented on jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/azurerules/LoadBalancer/RemoveUnusedLoadBalancer.java
> +                }
bakendPoolInstances ==null || bakendPoolInstances.isEmpty()

2023-07-21 13:45 UTC, merged