fix:sort in asset details associated policies
PaladinCloud/CE pull request #1668
Opened 2023-10-09 07:23 UTC by sidharthjain-zemoso

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List
any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Chore (no code changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also
list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] My commit message/PR follows the contribution guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# **Other information**:

List any documentation updates that are needed for the Wiki

2023-10-09 07:48 UTC, santhosh-challa submitted a review, later dismissed

2023-10-09 19:21 UTC, mkinchin-paladin requested changes
PR needs some change

2023-10-09 19:21 UTC, mkinchin-paladin commented on webapp/src/config/configurations.ts
> +      }
revert

2023-10-09 19:21 UTC, mkinchin-paladin commented on webapp/src/app/pacman-features/secondary-components/pacman-policy-violations/pacman-policy-violations.component.ts
> +      }
You have order and severityOrder here as an array. But all you care about is index in that array. 
Why don't convert those two into maps? Keys - severity levels, values - their assigned number/weights.
So then you will not need to use `indexOf` to search exact index, you just need to get element from the map.
Check out other columnsSortFunctionMap functions and you'll see how to do that, AssetGroupsComponent for example.

2023-10-12 06:57 UTC, plyubich requested changes

2023-10-12 06:57 UTC, plyubich commented on webapp/src/config/configurations.ts
> +         ISSUE_EMAIL_FROM_ID: 'notify@paladincloud.io',
Why do you have the email address hardcoded on the UI? API should take care of figuring it out or hard coding in API side. These type of updates must be API driven!

If this requires an API change, we should engage the api team for support.

As stated before, keep such business logic out of UI and if you encounter future scenarios of such behavior please add a task to get that dependency removed from the UI.

2023-11-02 06:40 UTC, santhosh-challa commented
@sidharthjain-zemoso Can we add a ticket for moving that email to API and move this?

2023-11-03 07:51 UTC, sidharthjain-zemoso commented
> @sidharthjain-zemoso Can we add a ticket for moving that email to API and move this?

Yes. We have a backend ticket for this.

2023-12-08 10:49 UTC, santhosh-challa commented
@plyubich as we added a ticket for API change, I am merging this.

2023-12-08 10:49 UTC, merged