fix:[CORE-1557] Ops alert qualys issue
PaladinCloud/CE pull request #1699
Opened 2023-10-16 10:43 UTC by AishwaryaKulkarni97

# Description

Ops alert should not be generated after user is notified of authentication issue

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Chore (no code changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Ran the qualys asset importer in saasdev

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] My commit message/PR follows the contribution guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# **Other information**:

List any documentation updates that are needed for the Wiki

2023-10-16 14:37 UTC, raviteja-mandala approved these changes

2023-10-18 06:01 UTC, santhosh-challa requested changes

2023-10-18 06:01 UTC, santhosh-challa commented on jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/jobs/HostAssetDataImporter.java
> -            Map<String,String> errorMap = new HashMap<>();
@AishwaryaKulkarni97 @raviteja-mandala This will completely swallow the error, instead, we just wanted not to raise this as an alert correct?

2023-10-23 10:13 UTC, santhosh-challa submitted a review, later dismissed

2023-10-25 08:20 UTC, santhosh-challa approved these changes

2023-10-25 08:20 UTC, merged