Port/ee to ce changes
PaladinCloud/CE pull request #1704
Opened 2023-10-16 13:42 UTC by ranadheer-b

Ported EE changes to CE repo

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Chore (no code changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also
list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] My commit message/PR follows the contribution guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# **Other information**:

List any documentation updates that are needed for the Wiki

2023-10-16 22:48 UTC, mkinchin-paladin requested changes
It's a huge PR, can you elaborate how it was tested? 
I understand that this is merge from EE to CE, but it doesn't mean that it shouldn't be tested.

2023-10-17 07:11 UTC, ranadheer-b commented
> It's a huge PR, can you elaborate how it was tested? I understand that this is merge from EE to CE, but it doesn't mean that it shouldn't be tested.

I have tested in localhost and added screenshots for respective commits now.

2023-10-18 00:00 UTC, mkinchin-paladin approved these changes

2023-10-18 05:30 UTC, santhosh-challa approved these changes

2023-10-18 06:30 UTC, santhosh-challa approved these changes

2023-10-18 06:32 UTC, merged