chore:[Devops-191] gpg key updated
PaladinCloud/CE pull request #1788
Opened 2023-11-08 05:43 UTC by rnithinpaladin

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List
any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Chore (no code changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also
list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] My commit message/PR follows the contribution guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# **Other information**:

List any documentation updates that are needed for the Wiki

2023-11-08 21:19 UTC, mkinchin-paladin requested changes
How it was tested? Is it possible to test?

2023-11-09 04:25 UTC, rnithinpaladin commented
> How it was tested? Is it possible to test?

@mkinchin-paladin Docker build was failing.

Once Gpg key is updated 
Docker build succeded.

2023-11-09 09:44 UTC, santhosh-challa approved these changes

2023-11-14 01:04 UTC, mkinchin-paladin commented
> > How it was tested? Is it possible to test?
> 
> @mkinchin-paladin Docker build was failing.
> 
> Once Gpg key is updated Docker build succeded.

Nice

2023-11-14 01:04 UTC, mkinchin-paladin approved these changes

2023-11-14 10:16 UTC, merged