style: added ellipses for values in policy param widget
PaladinCloud/CE pull request #1793
Opened 2023-11-08 12:24 UTC by sidharthjain-zemoso

# Description
1. Fixed the lengthy values overflowing out of the widget by adding ellipsis to both the key and value.

Fixes # (issue)
Policy Param Widget in Policy Compliance

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Chore (no code changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also
list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] My commit message/PR follows the contribution guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# **Other information**:

List any documentation updates that are needed for the Wiki

2023-11-08 19:59 UTC, mkinchin-paladin requested changes
Provide test results: before and after.

2023-11-10 10:14 UTC, plyubich commented
Production code should always be neat and clean:
As a basic:
1. Format your code
2. Remove extra new lines
3. Standardize naming
4. Remove commented code
5. DO commented complex lines of code to explain logic
6. Extract duplicate code to a function

2023-12-08 10:58 UTC, santhosh-challa approved these changes

2023-12-08 10:59 UTC, santhosh-challa commented
@mkinchin-paladin @plyubich Please let me know if we are good to merge this.

2023-12-12 06:34 UTC, plyubich approved these changes
LGTM

2023-12-14 13:02 UTC, merged

2023-12-14 16:09 UTC, plyubich commented
@sidharthjain-zemoso there is a big white space gap between key and value, can that gap shrink more or be dynamic to a max size? 

Please discuss the Bharat how to improve the white space.

2023-12-14 16:38 UTC, sidharthjain-zemoso commented
> @sidharthjain-zemoso there is a big white space gap between key and value, can that gap shrink more or be dynamic to a max size?
> 
> Please discuss the Bharat how to improve the white space.
> 
> Also, instead of ellipses, have you tried to wrap values column? Users would want to see the full list of values instead of ...

It was an ask from steve in UIUX-443 to increase width of key. 
Before UIUX-443:
![image](https://github.com/PaladinCloud/CE/assets/97596144/c05c0844-9751-4a83-8f4d-7bbb70ba8f9f)

But I get your point. Will check with Bharat and see if we can improve it.