fix: user policies showing all autofix enabled
PaladinCloud/CE pull request #1794
Opened 2023-11-08 12:29 UTC by sidharthjain-zemoso

# Description
1. Fixed user policies showing all policies as autofix enabled.

Fixes # (issue)
User Policies

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also
list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] My commit message/PR follows the contribution guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# **Other information**:

List any documentation updates that are needed for the Wiki

2023-11-08 20:01 UTC, mkinchin-paladin requested changes
Provide test results. Add task to the title

2023-11-10 10:18 UTC, plyubich commented
Production code should always be neat and clean:
As a basic:
1. Format your code
2. Remove extra new lines
3. Standardize naming
4. Remove commented code
5. DO commented complex lines of code to explain logic
6. Extract duplicate code to a function

2023-11-14 01:07 UTC, mkinchin-paladin commented
@sidharthjain-zemoso any updates?

2023-12-11 06:48 UTC, santhosh-challa approved these changes

2023-12-11 06:49 UTC, merged