Porting changes from
PaladinCloud/CE pull request #1799
Opened 2023-11-09 04:47 UTC by ranadheer-b

Added new tenable screen
fixed Titles of Compliance Trend and Trend Of Total And Compliant Assets alignment
Calendars and graph plots are getting refreshed when switched between Asset Groups

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also
list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] My commit message/PR follows the contribution guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# **Other information**:

List any documentation updates that are needed for the Wiki

2023-11-10 10:17 UTC, plyubich requested changes
Production code should always be neat and clean:
As a basic:
1. Format your code
2. Remove extra new lines
3. Standardize naming
4. Remove commented code
5. DO commented complex lines of code to explain logic
6. Extract duplicate code to a function

2023-11-14 01:19 UTC, mkinchin-paladin commented
@ranadheer-b can we have a list of porting PRs here? Just for history and better understanding why this big PR is created.

2023-12-11 14:10 UTC, sidharthjain-zemoso commented
> @ranadheer-b can we have a list of porting PRs here? Just for history and better understanding why this big PR is created.

I have added ported PR's in the description.
Can you please review

2023-12-12 06:37 UTC, plyubich approved these changes

2023-12-14 05:21 UTC, merged