fix:[CORE-1662] s3 bucket deleted while running policy
PaladinCloud/CE pull request #1815
Opened 2023-11-12 18:51 UTC by AishwaryaKulkarni97

# Description

No such bucket found exception occurs when s3 bucket is deleted but policy is trying to access the bucket using AWS client. In this case, exception should be handled and status is unknown

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Chore (no code changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also
list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] My commit message/PR follows the contribution guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# **Other information**:

List any documentation updates that are needed for the Wiki

2023-11-13 08:30 UTC, plyubich requested changes
All PRs without proper screenshot(s) demonstrating the fix will be rejected.

Also, please correct spacings. Simply reformat the affected files in this PR.

2023-11-13 12:11 UTC, AishwaryaKulkarni97 commented
> All PRs without proper screenshot(s) demonstrating the fix will be rejected.
> 
> Also, please correct spacings. Simply reformat the affected files in this PR.

Made the required changes

2023-11-14 15:47 UTC, plyubich approved these changes

2023-11-15 04:34 UTC, merged

2023-11-15 18:24 UTC, mkinchin-paladin commented
@AishwaryaKulkarni97 Those screenshots are not exactly what was expected.
What was expected is to see not how you created something in AWS (I believe you can work with AWS easily), but exact results of you test. Like issue didn't appeared and exception being handled (if I understand correctly the whole purpose of this PR).