Style/disabled filter chips
PaladinCloud/CE pull request #1853
Opened 2023-11-17 12:44 UTC by sidharthjain-zemoso

# Description
Changed styles of disabled filters to differentiate it from enabled filter.

# Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Could you provide instructions so we can reproduce them? Please also
list any relevant details for your test configuration

Before:
![image](https://github.com/PaladinCloud/EE/assets/97596144/e3e3e0d6-8798-4f2d-9734-745412442867)

After:
![image](https://github.com/PaladinCloud/EE/assets/97596144/d1371798-78ad-4ce1-a9f5-a05bc613507c)

- [ ] Test A
- [ ] Test B

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] The commit message/PR follows our guidelines

# **Other information**:

2023-11-28 01:21 UTC, mkinchin-paladin approved these changes

2023-11-28 01:26 UTC, mkinchin-paladin requested changes
Is there ticket for these changes?

2023-11-28 06:35 UTC, sidharthjain-zemoso commented
> Is there ticket for these changes?

Yes we have a ticket - UIUX-497.

2023-11-29 02:43 UTC, mkinchin-paladin approved these changes

2023-11-29 23:48 UTC, mkinchin-paladin requested changes
Do not merge, this needs to be discussed with @plyubich

2023-12-12 06:31 UTC, plyubich requested changes

2023-12-12 11:01 UTC, sidharthjain-zemoso commented on webapp/src/app/shared/table-filters/table-filters.component.html
> +        <app-table-filter-chip
Formatted that block.

2023-12-14 07:16 UTC, plyubich approved these changes

2023-12-18 05:20 UTC, merged