bug:[CORE-1333] correct datatype for createdDate and modifiedDate in …
PaladinCloud/CE pull request #1908
Opened 2023-11-29 13:51 UTC by shefalibisht1992

…asset groups

# Description

Datatype for asset group createdDate and modifiedDate is varchar in database, correctting it to timestamp.
![ag1](https://github.com/PaladinCloud/CE/assets/120437735/59ebac07-ed70-42f0-a404-e7923cd18613)
![aset3](https://github.com/PaladinCloud/CE/assets/120437735/7edeba50-0110-424a-a3ee-581584619ea1)
![asset-grp1](https://github.com/PaladinCloud/CE/assets/120437735/d29e46cd-368f-4193-83f4-2d38cbf6837c)
![assetgrp2](https://github.com/PaladinCloud/CE/assets/120437735/d3291df9-68f4-49b3-9d26-94a1491ae3a2)

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also
list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] My commit message/PR follows the contribution guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# **Other information**:

List any documentation updates that are needed for the Wiki

2023-11-29 15:19 UTC, plyubich requested changes
Please correct formatting of the code

2023-11-30 11:22 UTC, shefalibisht1992 commented
> Please correct formatting of the code

done.

2023-12-05 05:58 UTC, santhosh-challa approved these changes

2023-12-05 19:20 UTC, plyubich requested changes
Please work on formatting

2023-12-11 19:25 UTC, shefalibisht1992 commented on installer/resources/pacbot_app/files/DB.sql
> +CALL correct_datatype_for_dates_in_asset_groups();
Done.

2023-12-22 09:10 UTC, santhosh-challa approved these changes

2023-12-22 10:13 UTC, raviteja-mandala approved these changes

2023-12-22 10:27 UTC, merged