fix:[PLG-486] updating error logs
PaladinCloud/CE pull request #2130
Opened 2024-03-01 12:55 UTC by akashpaladin

## Description

Please include a summary of the changes and the related issues. Please also include relevant motivation and context. List
any dependencies that are required for this change.

### Problem

### Solution

## Fixes # (issue if any)

## Type of change

**Please delete options that are not relevant.**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Chore (no code changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

![image](https://github.com/PaladinCloud/CE/assets/114460784/1ddeb2df-8436-4d5b-805a-e53d15043b0c)

- [ ] Test A
- [ ] Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My commit message/PR follows the contribution guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## **Other Information**:

## List any documentation updates that are needed for the Wiki

2024-03-01 12:58 UTC, arunpaladin approved these changes

2024-03-05 03:27 UTC, arunpaladin approved these changes

2024-03-06 08:37 UTC, rnithinpaladin approved these changes

2024-03-06 20:39 UTC, plyubich requested changes
please check PR 2129 for same comments

2024-03-07 04:42 UTC, plyubich approved these changes

2024-03-07 05:00 UTC, merged