feat:[PLG-561] Only show one System assetgroup and do not create rapid7 assetgroup
PaladinCloud/CE pull request #2219
Opened 2024-05-21 20:22 UTC by akashpaladin

[PLG-561]

## Description

Please include a summary of the changes and the related issues. Please also include relevant motivation and context. List
any dependencies that are required for this change.

### Problem

### Solution

## Fixes # (issue if any)

## Type of change

**Please delete options that are not relevant.**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Chore (no code changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also
list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] My commit message/PR follows the contribution guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## **Other Information**:

## List any documentation updates that are needed for the Wiki

2024-05-21 21:49 UTC, arunpaladin approved these changes

2024-05-22 05:10 UTC, plyubich approved these changes

2024-05-22 05:14 UTC, plyubich requested changes

2024-05-22 05:14 UTC, plyubich commented on installer/resources/pacbot_app/files/DB.sql
> +UPDATE cf_AssetGroupDetails SET groupType = 'system' where groupType = 'System';
@santhosh-challa should we have this update statement in the repo, or we do a one time migration and keep updates out of the repo?

2024-05-22 05:15 UTC, plyubich requested changes
@santhosh-challa please see this PR's update statement

2024-05-22 06:32 UTC, rnithinpaladin approved these changes

2024-05-22 07:35 UTC, AnandPaladin approved these changes

2024-05-22 07:38 UTC, merged