fix: aws policy url bug fixes
PaladinCloud/CE pull request #748
Opened 2023-01-10 04:22 UTC by akashpaladin

# Description

Resolving url bug fixes and severity miss matches

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also
list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] The commit message/PR follows our guidelines

# **Other information**:

2023-01-10 11:16 UTC, dheerajkholia-paladin commented on installer/resources/pacbot_app/files/DB.sql
> +UPDATE cf_RuleInstance severity = 'critical', ruleParams = '{\"params\":[{\"key\":\"ruleKey\",\"value\":\"check-for-es-node-to-node-encrypted\",\"encrypt\":false},{\"encrypt\":false,\"value\":\"criti
Please correct this query

2023-01-10 18:29 UTC, akashpaladin commented on installer/resources/pacbot_app/files/DB.sql
> +UPDATE cf_RuleInstance severity = 'critical', ruleParams = '{\"params\":[{\"key\":\"ruleKey\",\"value\":\"check-for-es-node-to-node-encrypted\",\"encrypt\":false},{\"encrypt\":false,\"value\":\"criti
done

2023-01-12 04:36 UTC, dheerajkholia-paladin approved these changes

2023-01-16 09:50 UTC, santhosh-challa approved these changes

2023-01-20 12:54 UTC, dheerajkholia-paladin requested changes
Update the sql changes in new policy table

2023-01-25 04:24 UTC, dheerajkholia-paladin approved these changes

2023-01-25 04:24 UTC, merged