Fix: policy-violation-desc.html
PaladinCloud/CE pull request #894
Opened 2023-03-01 01:33 UTC by Preston-Dailey

# Description

Changed Creation date to Date Created and added a time stamp of the current day. 

Fixes #885

## Fix

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Viewed the text in a view window it was a text only change.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] My commit message/PR follows the contribution guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# **Other information**:

This is my first ever pull request.  I assumed time stamp meant current time.  Thanks for letting me try to contribute, hopefully I can learn from this.

2023-03-01 01:34 UTC, Preston-Dailey commented
Thanks for taking the time to check this.  Let me know anything I can do to make it better or contribute in another area.

2023-03-01 08:03 UTC, plyubich requested changes

2023-03-01 08:03 UTC, plyubich commented on webapp/src/app/pacman-features/secondary-components/policy-violation-desc/policy-violation-desc.component.html
> +            Date Created 2/28/2023
The column name should not contain a hardcoded date value. Please remove 2/28/2023.

The actual value for this is coming from line 74

2023-03-02 16:42 UTC, Preston-Dailey commented
Awesome, thanks John!

2023-03-29 15:15 UTC, plyubich approved these changes
looks good

2023-04-06 13:11 UTC, merged