Added: violationID in details UI
PaladinCloud/CE pull request #966
Opened 2023-03-15 07:22 UTC by arifa11111

# Description

Display ViolationID in the Details UI

Fixes #884 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Chore (no code changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also
list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [x] My commit message/PR follows the contribution guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# **Other information**:

List any documentation updates that are needed for the Wiki

### Attachment
![Screenshot from 2023-03-15 12-52-08](https://user-images.githubusercontent.com/101788554/225235843-a7250104-6739-482c-bf9f-ea4e9ba5eefb.png)

2023-03-15 10:43 UTC, abdulkudduszemoso commented on webapp/src/app/pacman-features/secondary-components/policy-violation-desc/policy-violation-desc.component.ts
> +  ViolationIDParams: any;
Can we give proper data type here if possible, other then "any"

2023-03-15 12:20 UTC, astra1 requested changes

2023-03-15 12:20 UTC, astra1 commented on webapp/src/app/pacman-features/secondary-components/policy-violation-desc/policy-violation-desc.component.ts
> +  Params: any;
class properties should be written in camelCase

2023-03-15 12:20 UTC, astra1 commented on webapp/src/app/pacman-features/secondary-components/policy-violation-desc/policy-violation-desc.component.html
> +        <div class="policy-violation-label-content" [innerHTML]="Params.issueId" title="{{Params.issueId}}">
if `Params.issueId` doesn't contain any [entities](https://developer.mozilla.org/en-US/docs/Glossary/Entity), than you shouldn't use [innerHTML] property binding, use instead one-way binding, eg. `<div class="policy-violation-label-content" ...>{{ params.issueId }}</div>`

2023-03-15 13:29 UTC, astra1 commented on webapp/src/app/pacman-features/secondary-components/policy-violation-desc/policy-violation-desc.component.html
> +            violation ID</div>
please, capitalize the first letter `violation ID` to `Violation ID`

2023-03-15 15:05 UTC, plyubich approved these changes
good solution - approved

2023-03-16 08:23 UTC, sidharthjain-zemoso approved these changes

2023-03-17 08:43 UTC, santhosh-challa approved these changes

2023-03-17 08:44 UTC, merged

2023-03-17 22:04 UTC, PaladinCloudJohn commented
Thank you, @arifa11111, for being a contributor. Congrats on your first Paladin Cloud merge.